# Generated by Django 3.0.8 on 2020-07-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_auto_20200719_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
