# Generated by Django 3.0.8 on 2020-07-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_myuser_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='position',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_doc',
            field=models.BooleanField(default=False),
        ),
    ]
