# Generated by Django 3.0.8 on 2020-07-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_auto_20200728_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='pat_id',
            new_name='p_id',
        ),
    ]
